swagger: '2.0'
info:
  description: API for sparkle midpoint
  version: 0.1.0
  title: sparkle-midpoint
paths:
  /:
    get:
      summary: Root endpoint
      produces:
        - application/json
      responses:
        200:
          description: Returns basic application informations
          schema:
            $ref: '#/definitions/Info'
  /agent:
    post:
      summary: Creates new agent
      produces:
        - application/json
      responses:
        201:
          description: Agent created successfully
          schema:
            $ref: '#/definitions/Agent'
    delete:
      summary: Disconnects and remove agent
definitions:
  Agent:
    type: object
    properties:
      id:
        type: string
  Info:
    type: object
    properties:
      name:
        type: string
      version:
        $ref: '#/definitions/Version' 
  Version:
    type: object
    required:
    - major
    - minor
    - build
    properties:
      major:
        type: integer
      minor:
        type: integer
      build:
        type: integer
  Error:
    type: object
    properties:
      code:
        type: integer
      description:
        type: string
