swagger: '2.0'
info:
  description: API for sparkle midpoint
  version: 0.1.0
  title: sparkle-midpoint
paths:
  /:
    get:
      summary: Root endpoint, returns basic server information
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Info'
  /agent:
    post:
      summary: Creates new connector agent
      produces:
        - application/json  
      responses:
        201:
          description: Agent created successfully, agent_id is returned
          schema:
            $ref: '#/definitions/Agent'
        400:
          description: Something went wrong, see error.description for more
          schema:
            $ref: '#/definitions/Error'
    delete:
      summary: Disconnects and removes agenti
      requestBody:
        description: Agent to disconnect
        required: true
        content:
          application/json:
            schema:
              '#/definitions/Agent'
      responses:
        200:
          description: Agent removed and disconnected successfully
        400:
          description: Something went wrong, agent should be disconnected and removed anyway
          schema:
            $ref: '#/definitions/Error'
  /devices:
    get:
      summary: Returns list of connected devices
      produces:
        - application/json
      requestBody:
        description: Agent which should be used to send connector request
        required: true
        content:
          application/json:
            schema:
              '#/definitions/Agent'
      responses:
        200:
          description: Devices fetched successfully
          schema:
            $ref: '#/definitions/Devices'
        400:
          description: Something went wrong
          schema:
            $ref: '#/definitions/Error'
  /device/state:
    get:
      summary: Returns device state
      produces:
        - application/json
      requestBody:
        description: Device which state should be returned
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/DeviceRequest'
      responses:
        200:
          description: Device state fetched successfully
          schema:
            $ref: '#/definitions/DeviceStateResponse'
        400:
          description: Something went wrong
          schema:
            $ref: '#/definitions/Error'
    put:
      summary: Switches device state
  /device/datasheet:
    get: 
      summary: Returns device datasheet
  /device/value:
    get:
      summary: Return value of sensor device
definitions:
  DeviceId:
    type: object
    properties:
      id:
        type: integer
      agent:
        $ref: '#/definitions/Agent'
  DeviceDatasheet:
    type: object
  DeviceStateResponse:
    type: object
    properties:
      state:
        type: integer
  Devices:
    type: object
    properties:
      devices:
        type: array
        items:
          $ref: '#/definitions/Device'
  Device:
    type: object
    properties:
      id:
        type: integer
      type:
        type: integer
      name:
        type: string
      description:
        type: string 
  SensorValue:
    type: object
    properties:
      value:
        type: float
  Agent:
    type: object
    properties:
      id:
        type: string
  Info:
    type: object
    properties:
      name:
        type: string
      version:
        $ref: '#/definitions/Version' 
  Version:
    type: object
    required:
    - major
    - minor
    - build
    properties:
      major:
        type: integer
      minor:
        type: integer
      build:
        type: integer
  Error:
    type: object
    properties:
      code:
        type: integer
      description:
        type: string
