swagger: '2.0'
info:
  description: Design of dashboo syncer
  version: 0.1.0
  title: Dashboo Syncer
paths:
  /:
    get:
      summary: Version endpoint
      produces:
        - application/json
      responses:
        200:
          description: return syncer version
          schema:
            $ref: '#/definitions/Version'
  /sync/{user_id}:
    get:
      summary: Fetch synchronized events
      produces:
        - application/json
      parameters:
        - in: path
          name: user_id
          schema:
            type: integer
          required: True
      responses:
        200:
          description: return events
          schema:
            $ref: '#/definitions/EventsWrapper'
    put:
      summary: Update sync job
      parameters:
        - in: path
          name: user_id
          schema:
            type: integer
          required: True
      responses:
        201
    post:
      summary: Create sync job
      parameters:
        - in: path
          name: user_id
          schema:
            type: integer
          required: True
      responses:
        201
        400
  /sync/{user_id}/status:
    get:
      summary: Get status of sync job

  /sync/{user_id}/abort:
    put:

definitions:
  Error:
    type: object
    properties:
      code:
        type: integer
      description:
        type: string
  EventsWrapper:
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/Event'
      job_id:
        type: string
  Event:
    type: object
    required:
      - id
    properties:
      id:
        type: integer
  Version:
    type: object
    required:
    - build
    - version
    - name
    properties:
      build:
        type: string
      version:
        type: string
      name:
        type: string
