# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from . import util


class DeviceValue(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, values: object = None):  # noqa: E501
        """DeviceValue - a model defined in Swagger

        :param values: The values of this DeviceValue.  # noqa: E501
        :type values: object
        """
        self.swagger_types = {
            'values': object
        }

        self.attribute_map = {
            'values': 'values'
        }

        self._values = values

    @classmethod
    def from_dict(cls, dikt) -> 'DeviceValue':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DeviceValue of this DeviceValue.  # noqa: E501
        :rtype: DeviceValue
        """
        return util.deserialize_model(dikt, cls)

    @property
    def values(self) -> object:
        """Gets the values of this DeviceValue.


        :return: The values of this DeviceValue.
        :rtype: object
        """
        return self._values

    @values.setter
    def values(self, values: object):
        """Sets the values of this DeviceValue.


        :param values: The values of this DeviceValue.
        :type values: object
        """

        self._values = values
