# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Device(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, type: int=None, name: str=None, description: str=None):  # noqa: E501
        """Device - a model defined in Swagger

        :param id: The id of this Device.  # noqa: E501
        :type id: int
        :param type: The type of this Device.  # noqa: E501
        :type type: int
        :param name: The name of this Device.  # noqa: E501
        :type name: str
        :param description: The description of this Device.  # noqa: E501
        :type description: str
        """
        self.swagger_types = {
            'id': int,
            'type': int,
            'name': str,
            'description': str
        }

        self.attribute_map = {
            'id': 'id',
            'type': 'type',
            'name': 'name',
            'description': 'description'
        }

        self._id = id
        self._type = type
        self._name = name
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'Device':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Device of this Device.  # noqa: E501
        :rtype: Device
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Device.


        :return: The id of this Device.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Device.


        :param id: The id of this Device.
        :type id: int
        """

        self._id = id

    @property
    def type(self) -> int:
        """Gets the type of this Device.


        :return: The type of this Device.
        :rtype: int
        """
        return self._type

    @type.setter
    def type(self, type: int):
        """Sets the type of this Device.


        :param type: The type of this Device.
        :type type: int
        """

        self._type = type

    @property
    def name(self) -> str:
        """Gets the name of this Device.


        :return: The name of this Device.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Device.


        :param name: The name of this Device.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this Device.


        :return: The description of this Device.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Device.


        :param description: The description of this Device.
        :type description: str
        """

        self._description = description
