# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SensorDeviceDatasheetDatasheet(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, labels: List[str]=None):  # noqa: E501
        """SensorDeviceDatasheetDatasheet - a model defined in Swagger

        :param labels: The labels of this SensorDeviceDatasheetDatasheet.  # noqa: E501
        :type labels: List[str]
        """
        self.swagger_types = {
            'labels': List[str]
        }

        self.attribute_map = {
            'labels': 'labels'
        }

        self._labels = labels

    @classmethod
    def from_dict(cls, dikt) -> 'SensorDeviceDatasheetDatasheet':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SensorDeviceDatasheet_datasheet of this SensorDeviceDatasheetDatasheet.  # noqa: E501
        :rtype: SensorDeviceDatasheetDatasheet
        """
        return util.deserialize_model(dikt, cls)

    @property
    def labels(self) -> List[str]:
        """Gets the labels of this SensorDeviceDatasheetDatasheet.


        :return: The labels of this SensorDeviceDatasheetDatasheet.
        :rtype: List[str]
        """
        return self._labels

    @labels.setter
    def labels(self, labels: List[str]):
        """Sets the labels of this SensorDeviceDatasheetDatasheet.


        :param labels: The labels of this SensorDeviceDatasheetDatasheet.
        :type labels: List[str]
        """

        self._labels = labels
