# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from . import util


class SwitchableDeviceDatasheetDatasheet(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, states: List[int] = None):  # noqa: E501
        """SwitchableDeviceDatasheetDatasheet - a model defined in Swagger

        :param states: The states of this SwitchableDeviceDatasheetDatasheet.  # noqa: E501
        :type states: List[int]
        """
        self.swagger_types = {
            'states': List[int]
        }

        self.attribute_map = {
            'states': 'states'
        }

        self._states = states

    @classmethod
    def from_dict(cls, dikt) -> 'SwitchableDeviceDatasheetDatasheet':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SwitchableDeviceDatasheet_datasheet of this SwitchableDeviceDatasheetDatasheet.  # noqa: E501
        :rtype: SwitchableDeviceDatasheetDatasheet
        """
        return util.deserialize_model(dikt, cls)

    @property
    def states(self) -> List[int]:
        """Gets the states of this SwitchableDeviceDatasheetDatasheet.


        :return: The states of this SwitchableDeviceDatasheetDatasheet.
        :rtype: List[int]
        """
        return self._states

    @states.setter
    def states(self, states: List[int]):
        """Sets the states of this SwitchableDeviceDatasheetDatasheet.


        :param states: The states of this SwitchableDeviceDatasheetDatasheet.
        :type states: List[int]
        """

        self._states = states
