# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SwitchDeviceStateQuery(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, device_id: int=None, agent: Agent=None, state: DeviceState=None):  # noqa: E501
        """SwitchDeviceStateQuery - a model defined in Swagger

        :param device_id: The device_id of this SwitchDeviceStateQuery.  # noqa: E501
        :type device_id: int
        :param agent: The agent of this SwitchDeviceStateQuery.  # noqa: E501
        :type agent: Agent
        :param state: The state of this SwitchDeviceStateQuery.  # noqa: E501
        :type state: DeviceState
        """
        self.swagger_types = {
            'device_id': int,
            'agent': Agent,
            'state': DeviceState
        }

        self.attribute_map = {
            'device_id': 'device_id',
            'agent': 'agent',
            'state': 'state'
        }

        self._device_id = device_id
        self._agent = agent
        self._state = state

    @classmethod
    def from_dict(cls, dikt) -> 'SwitchDeviceStateQuery':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SwitchDeviceStateQuery of this SwitchDeviceStateQuery.  # noqa: E501
        :rtype: SwitchDeviceStateQuery
        """
        return util.deserialize_model(dikt, cls)

    @property
    def device_id(self) -> int:
        """Gets the device_id of this SwitchDeviceStateQuery.


        :return: The device_id of this SwitchDeviceStateQuery.
        :rtype: int
        """
        return self._device_id

    @device_id.setter
    def device_id(self, device_id: int):
        """Sets the device_id of this SwitchDeviceStateQuery.


        :param device_id: The device_id of this SwitchDeviceStateQuery.
        :type device_id: int
        """

        self._device_id = device_id

    @property
    def agent(self) -> Agent:
        """Gets the agent of this SwitchDeviceStateQuery.


        :return: The agent of this SwitchDeviceStateQuery.
        :rtype: Agent
        """
        return self._agent

    @agent.setter
    def agent(self, agent: Agent):
        """Sets the agent of this SwitchDeviceStateQuery.


        :param agent: The agent of this SwitchDeviceStateQuery.
        :type agent: Agent
        """

        self._agent = agent

    @property
    def state(self) -> DeviceState:
        """Gets the state of this SwitchDeviceStateQuery.


        :return: The state of this SwitchDeviceStateQuery.
        :rtype: DeviceState
        """
        return self._state

    @state.setter
    def state(self, state: DeviceState):
        """Sets the state of this SwitchDeviceStateQuery.


        :param state: The state of this SwitchDeviceStateQuery.
        :type state: DeviceState
        """

        self._state = state
