# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from . import util


class SwitchDeviceStateQuery(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, state: DeviceState = None):  # noqa: E501
        """SwitchDeviceStateQuery - a model defined in Swagger

        :param state: The state of this SwitchDeviceStateQuery.  # noqa: E501
        :type state: DeviceState
        """
        self.swagger_types = {
            'state': DeviceState
        }

        self.attribute_map = {
            'state': 'state'
        }

        self._state = state

    @classmethod
    def from_dict(cls, dikt) -> 'SwitchDeviceStateQuery':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SwitchDeviceStateQuery of this SwitchDeviceStateQuery.  # noqa: E501
        :rtype: SwitchDeviceStateQuery
        """
        return util.deserialize_model(dikt, cls)

    @property
    def state(self) -> DeviceState:
        """Gets the state of this SwitchDeviceStateQuery.


        :return: The state of this SwitchDeviceStateQuery.
        :rtype: DeviceState
        """
        return self._state

    @state.setter
    def state(self, state: DeviceState):
        """Sets the state of this SwitchDeviceStateQuery.


        :param state: The state of this SwitchDeviceStateQuery.
        :type state: DeviceState
        """

        self._state = state
