# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TaskId(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, task_id: str=None):  # noqa: E501
        """TaskId - a model defined in Swagger

        :param task_id: The task_id of this TaskId.  # noqa: E501
        :type task_id: str
        """
        self.swagger_types = {
            'task_id': str
        }

        self.attribute_map = {
            'task_id': 'task_id'
        }

        self._task_id = task_id

    @classmethod
    def from_dict(cls, dikt) -> 'TaskId':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TaskId of this TaskId.  # noqa: E501
        :rtype: TaskId
        """
        return util.deserialize_model(dikt, cls)

    @property
    def task_id(self) -> str:
        """Gets the task_id of this TaskId.


        :return: The task_id of this TaskId.
        :rtype: str
        """
        return self._task_id

    @task_id.setter
    def task_id(self, task_id: str):
        """Sets the task_id of this TaskId.


        :param task_id: The task_id of this TaskId.
        :type task_id: str
        """

        self._task_id = task_id
