name: sparkle-midpoint ci pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive
      - name: Install dependencies
        run: ./bin/deps.sh
      - name: Setup virtual environment
        run: ./bin/venv.sh
      - name: Run unit tests
        run: ./bin/run_unit_tests.sh
      - name: Generate test coverage report
        run: |
          ./venv/bin/coverage report -m
          ./venv/bin/coverage html
          mkdir cov && mv ./htmlcov cov 
      - name: Build docker container
        run: docker build --tag sparkle-midpoint --file ./misc/Dockerfile .
      - name: Create docker network
        run: docker network create sparkle-net
      - name: Run integration tests
        run: ./bin/run_integration_tests.sh
        env:
          SPARKLE_TEST_ENV: 1
      - name: Archive test coverage artifacts
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-cov
          path: cov
      - name: Push docker container
        if: github.ref == 'refs/heads/dev'
        run: |
          docker login --username ${{ secrets.DOCKER_AUTH_LOGIN }} --password ${{ secrets.DOCKER_AUTH_TOKEN }}
          docker tag sparkle-midpoint ${{ secrets.DOCKER_AUTH_LOGIN }}/sparkle-midpoint 
          docker push ${{ secrets.DOCKER_AUTH_LOGIN }}/sparkle-midpoint
