name: sparkle-midpoint ci pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive
      - name: Change scripts permissions
        run: chmod +x ./bin/*
      - name: Install dependencies
        run: ./bin/deps.sh
      - name: Setup virtual environment
        run: ./bin/venv.sh
      - name: Run unit tests
        run: ./bin/run_unit_tests.sh
      - name: Generate unit test coverage report
        run: ./bin/generate_ut_test_cov.sh
      - name: Build docker container
        run: docker build --tag sparkle-midpoint --file ./misc/Dockerfile .
      - name: Create docker network
        run: docker network create sparkle-net
      - name: Fetch sparkle-db scheme
        run: |
          git clone --single-branch --branch dev https://github.com/sparkle-sh/sparkle-db 
          cp sparkle-db/misc/*.sql ./misc
      - name: Run integration tests
        run: |
          mkdir ./sparkle-midpoint-cov
          rm -r logs > /dev/null 2>&1
          mkdir ./logs
          ./bin/run_integration_tests.sh
        env:
          SPARKLE_TEST_ENV: 1
      - name: Save integration tests logs
        run: |
          ./bin/save_tests_logs.sh > /dev/null
        if: always()
      - name: Archive integration tests logs
        uses: actions/upload-artifact@v2
        with:
          name: test-logs
          path: logs
          # - name: Generate integration tests coverage report
          #run: ./bin/generate_it_test_cov.sh
      - name: Archive unit test coverage artifacts
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-cov
          path: cov
          #      - name: Archive integration test coverage artifacts
          #uses: actions/upload-artifact@v2
          #with:
          #name: integration-test-cov
          #path: it-cov
      - name: Generate swagger documentation for API
        run: ./bin/gen_api_docs.py < ./misc/swagger.yaml > api-docs.html
      - name: Archive documentation
        uses: actions/upload-artifact@v2
        with:
          name: api-docs
          path: ./api-docs.html
      - name: Push docker container
        if: github.ref == 'refs/heads/dev'
        run: |
          docker login --username ${{ secrets.DOCKER_AUTH_LOGIN }} --password ${{ secrets.DOCKER_AUTH_TOKEN }}
          docker tag sparkle-midpoint ${{ secrets.DOCKER_AUTH_LOGIN }}/sparkle-midpoint 
          docker push ${{ secrets.DOCKER_AUTH_LOGIN }}/sparkle-midpoint

